name: bushfires
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - gdal
  - pyogrio
  - jupyterlab
  - pyproj
  - geopandas
  - papermill
  - folium
  - pandas
  - requests
  - numpy